/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

public class App {
    public static void main(String[] _args) {
	Dialog ep = new Dialog();
	ep.entryPoint();
    }
}
